name: Docker Image CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ master ]

jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true # push to registry
          pull: true # always fetch the latest base images
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          tags: ghcr.io/rmoriz/obs-web:latest, rmoriz/obs-web:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
